SCR_MapConfig {
 m_iMapMode MHJ_PLANNER
 m_LayersConfig SCR_MapLayersBase "{C4E8A27B1F906DA2}" : "{3CAC09C3E89190F7}Configs/Map/MapLayersDefault.conf" {
 }
 m_MapPropsConfig SCR_MapPropsBase "{C4E8A27B1F906DA3}" : "{AF65563F653FED68}Configs/Map/MapPropsDefault.conf" {
 }
 m_aUIComponents {
  SCR_MapMarkersUI "{C4E8A27B1F906DC1}" {
  }
  SCR_MapUIElementContainer "{C4E8A27B1F906DC2}" {
   m_bShowSpawnPoints 0
   m_bShowTasks 1
  }
 }
 m_bEnableGrid 0
 m_DescriptorVisibilityConfig SCR_MapDescriptorVisibilityBase "{C4E8A27B1F906DA4}" : "{4FFDB559B60FC7BC}Configs/Map/MapDescriptorVisibilityDefault.conf" {
 }
 m_DescriptorDefaultsConfig SCR_MapDescriptorDefaults "{C4E8A27B1F906DA5}" : "{FF6B20825D4A566C}Configs/Map/MapDescriptorDefaults.conf" {
 }
}
